# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/sysstate.yaml instead

"""
    demo_syslog(P, name="Test flight"; duration=10)

Create a demo flight log  with given name [String] and duration [s] as StructArray. P is the number of tether
particles.
"""
function demo_syslog(P, name="Test flight"; duration=10)
    max_height = 6.03
    steps   = Int(duration * se().sample_freq) + 1
    time_vec = Vector{Float64}(undef, steps)
    t_sim_vec = Vector{Float64}(undef, steps)
    sys_state_vec = Vector{Int16}(undef, steps)
    cycle_vec = Vector{Int16}(undef, steps)
    fig_8_vec = Vector{Int16}(undef, steps)
    e_mech_vec = Vector{Float64}(undef, steps)
    orient_vec = Vector{MVector{4, Float32}}(undef, steps)
    turn_rates_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    elevation_vec = Vector{MyFloat}(undef, steps)
    azimuth_vec = Vector{MyFloat}(undef, steps)
    l_tether_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    v_reelout_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    force_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    depower_vec = Vector{MyFloat}(undef, steps)
    steering_vec = Vector{MyFloat}(undef, steps)
    kcu_steering_vec = Vector{MyFloat}(undef, steps)
    set_steering_vec = Vector{MyFloat}(undef, steps)
    heading_vec = Vector{MyFloat}(undef, steps)
    heading_rate_vec = Vector{MyFloat}(undef, steps)
    course_vec = Vector{MyFloat}(undef, steps)
    bearing_vec = Vector{MyFloat}(undef, steps)
    attractor_vec = Vector{MVector{2, MyFloat}}(undef, steps)
    v_app_vec = Vector{MyFloat}(undef, steps)
    v_wind_gnd_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    v_wind_200m_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    v_wind_kite_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    AoA_vec = Vector{MyFloat}(undef, steps)
    side_slip_vec = Vector{MyFloat}(undef, steps)
    alpha3_vec = Vector{MyFloat}(undef, steps)
    alpha4_vec = Vector{MyFloat}(undef, steps)
    CL2_vec = Vector{MyFloat}(undef, steps)
    CD2_vec = Vector{MyFloat}(undef, steps)
    aero_force_b_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    aero_moment_b_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    twist_angles_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    vel_kite_vec = Vector{MVector{3, MyFloat}}(undef, steps)
    acc_vec = Vector{MyFloat}(undef, steps)
    X_vec = Vector{MVector{P, MyFloat}}(undef, steps)
    Y_vec = Vector{MVector{P, MyFloat}}(undef, steps)
    Z_vec = Vector{MVector{P, MyFloat}}(undef, steps)
    set_torque_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    set_speed_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    set_force_vec = Vector{MVector{4, MyFloat}}(undef, steps)
    roll_vec = Vector{MyFloat}(undef, steps)
    pitch_vec = Vector{MyFloat}(undef, steps)
    yaw_vec = Vector{MyFloat}(undef, steps)
    var_01_vec = Vector{MyFloat}(undef, steps)
    var_02_vec = Vector{MyFloat}(undef, steps)
    var_03_vec = Vector{MyFloat}(undef, steps)
    var_04_vec = Vector{MyFloat}(undef, steps)
    var_05_vec = Vector{MyFloat}(undef, steps)
    var_06_vec = Vector{MyFloat}(undef, steps)
    var_07_vec = Vector{MyFloat}(undef, steps)
    var_08_vec = Vector{MyFloat}(undef, steps)
    var_09_vec = Vector{MyFloat}(undef, steps)
    var_10_vec = Vector{MyFloat}(undef, steps)
    var_11_vec = Vector{MyFloat}(undef, steps)
    var_12_vec = Vector{MyFloat}(undef, steps)
    var_13_vec = Vector{MyFloat}(undef, steps)
    var_14_vec = Vector{MyFloat}(undef, steps)
    var_15_vec = Vector{MyFloat}(undef, steps)
    var_16_vec = Vector{MyFloat}(undef, steps)
    for i in range(0, length=steps)
        state = demo_state(P, max_height * i/steps, i/se().sample_freq)
        elevation_vec[i+1] = asin(state.Z[end]/state.X[end])
        time_vec[i+1] = state.time
        t_sim_vec[i+1] = state.t_sim
        sys_state_vec[i+1] = state.sys_state
        cycle_vec[i+1] = state.cycle
        fig_8_vec[i+1] = state.fig_8
        e_mech_vec[i+1] = state.e_mech
        orient_vec[i+1] = state.orient
        turn_rates_vec[i+1] = state.turn_rates
        elevation_vec[i+1] = state.elevation
        azimuth_vec[i+1] = state.azimuth
        l_tether_vec[i+1] = state.l_tether
        v_reelout_vec[i+1] = state.v_reelout
        force_vec[i+1] = state.force
        depower_vec[i+1] = state.depower
        steering_vec[i+1] = state.steering
        kcu_steering_vec[i+1] = state.kcu_steering
        set_steering_vec[i+1] = state.set_steering
        heading_vec[i+1] = state.heading
        heading_rate_vec[i+1] = state.heading_rate
        course_vec[i+1] = state.course
        bearing_vec[i+1] = state.bearing
        attractor_vec[i+1] = state.attractor
        v_app_vec[i+1] = state.v_app
        v_wind_gnd_vec[i+1] = state.v_wind_gnd
        v_wind_200m_vec[i+1] = state.v_wind_200m
        v_wind_kite_vec[i+1] = state.v_wind_kite
        AoA_vec[i+1] = state.AoA
        side_slip_vec[i+1] = state.side_slip
        alpha3_vec[i+1] = state.alpha3
        alpha4_vec[i+1] = state.alpha4
        CL2_vec[i+1] = state.CL2
        CD2_vec[i+1] = state.CD2
        aero_force_b_vec[i+1] = state.aero_force_b
        aero_moment_b_vec[i+1] = state.aero_moment_b
        twist_angles_vec[i+1] = state.twist_angles
        vel_kite_vec[i+1] = state.vel_kite
        acc_vec[i+1] = state.acc
        X_vec[i+1] = state.X
        Y_vec[i+1] = state.Y
        Z_vec[i+1] = state.Z
        set_torque_vec[i+1] = state.set_torque
        set_speed_vec[i+1] = state.set_speed
        set_force_vec[i+1] = state.set_force
        roll_vec[i+1] = state.roll
        pitch_vec[i+1] = state.pitch
        yaw_vec[i+1] = state.yaw
        var_01_vec[i+1] = state.var_01
        var_02_vec[i+1] = state.var_02
        var_03_vec[i+1] = state.var_03
        var_04_vec[i+1] = state.var_04
        var_05_vec[i+1] = state.var_05
        var_06_vec[i+1] = state.var_06
        var_07_vec[i+1] = state.var_07
        var_08_vec[i+1] = state.var_08
        var_09_vec[i+1] = state.var_09
        var_10_vec[i+1] = state.var_10
        var_11_vec[i+1] = state.var_11
        var_12_vec[i+1] = state.var_12
        var_13_vec[i+1] = state.var_13
        var_14_vec[i+1] = state.var_14
        var_15_vec[i+1] = state.var_15
        var_16_vec[i+1] = state.var_16
    end
    StructArray{SysState{P}}((time_vec, t_sim_vec, sys_state_vec, cycle_vec, fig_8_vec, e_mech_vec, 
                              orient_vec, turn_rates_vec, elevation_vec, azimuth_vec, l_tether_vec, v_reelout_vec, 
                              force_vec, depower_vec, steering_vec, kcu_steering_vec, set_steering_vec, heading_vec, 
                              heading_rate_vec, course_vec, bearing_vec, attractor_vec, v_app_vec, v_wind_gnd_vec, 
                              v_wind_200m_vec, v_wind_kite_vec, AoA_vec, side_slip_vec, alpha3_vec, alpha4_vec, 
                              CL2_vec, CD2_vec, aero_force_b_vec, aero_moment_b_vec, twist_angles_vec, vel_kite_vec, 
                              acc_vec, X_vec, Y_vec, Z_vec, set_torque_vec, set_speed_vec, 
                              set_force_vec, roll_vec, pitch_vec, yaw_vec, var_01_vec, var_02_vec, 
                              var_03_vec, var_04_vec, var_05_vec, var_06_vec, var_07_vec, var_08_vec, 
                              var_09_vec, var_10_vec, var_11_vec, var_12_vec, var_13_vec, var_14_vec, 
                              var_15_vec, var_16_vec))
end
