# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/sysstate.yaml instead

"""
    save_log(logger::Logger, name="sim_log", compress=true;
                path="",
                colmeta = Dict(:var_01 => ["name" => "var_01"],
                               :var_02 => ["name" => "var_02"],
                               :var_03 => ["name" => "var_03"],
                               :var_04 => ["name" => "var_04"],
                               :var_05 => ["name" => "var_05"],
                               :var_06 => ["name" => "var_06"],
                               :var_07 => ["name" => "var_07"],
                               :var_08 => ["name" => "var_08"],
                               :var_09 => ["name" => "var_09"],
                               :var_10 => ["name" => "var_10"],
                               :var_11 => ["name" => "var_11"],
                               :var_12 => ["name" => "var_12"],
                               :var_13 => ["name" => "var_13"],
                               :var_14 => ["name" => "var_14"],
                               :var_15 => ["name" => "var_15"],
                               :var_16 => ["name" => "var_16"]
            ))

Save a fligh log from a logger as .arrow file. By default lz4 compression is used, 
if you use **false** as second parameter no compression is used.
"""
function save_log(logger::Logger, name="sim_log", compress=true;
    path="",
    colmeta = Dict(:var_01 => ["name" => "var_01"],
                   :var_02 => ["name" => "var_02"],
                   :var_03 => ["name" => "var_03"],
                   :var_04 => ["name" => "var_04"],
                   :var_05 => ["name" => "var_05"],
                   :var_06 => ["name" => "var_06"],
                   :var_07 => ["name" => "var_07"],
                   :var_08 => ["name" => "var_08"],
                   :var_09 => ["name" => "var_09"],
                   :var_10 => ["name" => "var_10"],
                   :var_11 => ["name" => "var_11"],
                   :var_12 => ["name" => "var_12"],
                   :var_13 => ["name" => "var_13"],
                   :var_14 => ["name" => "var_14"],
                   :var_15 => ["name" => "var_15"],
                   :var_16 => ["name" => "var_16"]
                  ))
    nl = length(logger)
    resize!(logger.time_vec, nl)
    resize!(logger.t_sim_vec, nl)
    resize!(logger.sys_state_vec, nl)
    resize!(logger.cycle_vec, nl)
    resize!(logger.fig_8_vec, nl)
    resize!(logger.e_mech_vec, nl)
    resize!(logger.orient_vec, nl)
    resize!(logger.elevation_vec, nl)
    resize!(logger.azimuth_vec, nl)
    resize!(logger.l_tether_vec, nl)
    resize!(logger.v_reelout_vec, nl)
    resize!(logger.force_vec, nl)
    resize!(logger.depower_vec, nl)
    resize!(logger.steering_vec, nl)
    resize!(logger.set_steering_vec, nl)
    resize!(logger.heading_vec, nl)
    resize!(logger.heading_rate_vec, nl)
    resize!(logger.course_vec, nl)
    resize!(logger.attractor_vec, nl)
    resize!(logger.v_app_vec, nl)
    resize!(logger.v_wind_gnd_vec, nl)
    resize!(logger.v_wind_200m_vec, nl)
    resize!(logger.v_wind_kite_vec, nl)
    resize!(logger.AoA_vec, nl)
    resize!(logger.alpha3_vec, nl)
    resize!(logger.alpha4_vec, nl)
    resize!(logger.CL2_vec, nl)
    resize!(logger.CD2_vec, nl)
    resize!(logger.vel_kite_vec, nl)
    resize!(logger.acc_vec, nl)
    resize!(logger.X_vec, nl)
    resize!(logger.Y_vec, nl)
    resize!(logger.Z_vec, nl)
    resize!(logger.set_torque_vec, nl)
    resize!(logger.set_speed_vec, nl)
    resize!(logger.set_force_vec, nl)
    resize!(logger.roll_vec, nl)
    resize!(logger.pitch_vec, nl)
    resize!(logger.yaw_vec, nl)
    resize!(logger.var_01_vec, nl)
    resize!(logger.var_02_vec, nl)
    resize!(logger.var_03_vec, nl)
    resize!(logger.var_04_vec, nl)
    resize!(logger.var_05_vec, nl)
    resize!(logger.var_06_vec, nl)
    resize!(logger.var_07_vec, nl)
    resize!(logger.var_08_vec, nl)
    resize!(logger.var_09_vec, nl)
    resize!(logger.var_10_vec, nl)
    resize!(logger.var_11_vec, nl)
    resize!(logger.var_12_vec, nl)
    resize!(logger.var_13_vec, nl)
    resize!(logger.var_14_vec, nl)
    resize!(logger.var_15_vec, nl)
    resize!(logger.var_16_vec, nl)
    flight_log = (sys_log(logger, name; colmeta))
    save_log(flight_log, compress; path)
end
