# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/sysstate.yaml instead

"""
    SysState{P}

Basic system state. One of these is saved per time step. P is the number
of tether particles.

$(TYPEDFIELDS)
"""
Base.@kwdef mutable struct SysState{P}
    "time since start of simulation [s]"
    time::Float64 = 0
    "time needed for one simulation timestep [s]"
    t_sim::Float64 = 0
    "state of system state control"
    sys_state::Int16 = 0
    "cycle number"
    cycle::Int16 = 0
    "number of the figure of eight of the current cycle"
    fig_8::Int16 = 0
    "mechanical energy [Wh]"
    e_mech::Float64 = 0
    "orientation of the kite (quaternion, order w,x,y,z)"
    orient::MVector{4, Float32} = [1.0, 0.0, 0.0, 0.0]
    "turn rates around the body fixed x, y and z axis [rad/s]"
    turn_rates::MVector{3, Float32} = 0
    "elevation angle [rad]"
    elevation::MyFloat = 0
    "azimuth angle in wind reference frame [rad]"
    azimuth::MyFloat = 0
    "tether length, tether 1 to 4 [m]"
    l_tether::MVector{4, MyFloat} = 0
    "reelout speed, tether 1 to 4 [m/s]"
    v_reelout::MVector{4, MyFloat} = 0
    "tether force, tether 1 to 4 [N]"
    force::MVector{4, MyFloat} = 0
    "depower settings [0..1]"
    depower::MyFloat = 0
    "actual steering [-1..1]"
    steering::MyFloat = 0
    "steering after the kcu, before applying offset and depower scaling [-1..1]"
    kcu_steering::MyFloat = 0
    "set value of the steering [-1..1]"
    set_steering::MyFloat = 0
    "heading angle [rad]"
    heading::MyFloat = 0
    "heading rate [rad/s]"
    heading_rate::MyFloat = 0
    "course angle [rad]"
    course::MyFloat = 0
    "bearing angle (set value of heading/ course) [rad]"
    bearing::MyFloat = 0
    "attractor coordinates (azimuth, elevation) [rad]"
    attractor::MVector{2, MyFloat} = [0.0, 0.0]
    "norm of apparent wind speed [m/s]"
    v_app::MyFloat = 0
    "wind vector at reference height [m/s]"
    v_wind_gnd::MVector{3, MyFloat} = [0.0, 0.0, 0.0]
    "wind vector at 200m height [m/s]"
    v_wind_200m::MVector{3, MyFloat} = [0.0, 0.0, 0.0]
    "wind vector at the height of the kite [m/s]"
    v_wind_kite::MVector{3, MyFloat} = [0.0, 0.0, 0.0]
    "angle of attack [rad]"
    AoA::MyFloat = 0
    "side slip angle [rad]"
    side_slip::MyFloat = 0
    "angle of attack at particle C [rad]"
    alpha3::MyFloat = 0
    "angle of attack at particle D [rad]"
    alpha4::MyFloat = 0
    "lift coefficient"
    CL2::MyFloat = 0
    "drag coefficient"
    CD2::MyFloat = 0
    "velocity vector of the kite [m/s]"
    vel_kite::MVector{3, MyFloat} = [0.0, 0.0, 0.0]
    "acceleration [m/s²]"
    acc::MyFloat = 0
    "vector of particle positions in x [m]"
    X::MVector{P, MyFloat} = zeros(P)
    "vector of particle positions in y [m]"
    Y::MVector{P, MyFloat} = zeros(P)
    "vector of particle positions in z [m]"
    Z::MVector{P, MyFloat} = zeros(P)
    "torque setting, winch 1..4       [Nm]"
    set_torque::MVector{4, MyFloat} = 0
    "speed setting, winch 1..4       [m/s]"
    set_speed::MVector{4, MyFloat} = 0
    "force setting, winch 1..4         [N]"
    set_force::MVector{4, MyFloat} = 0
    "roll angle [rad]"
    roll::MyFloat = 0
    "pitch angle [rad]"
    pitch::MyFloat = 0
    "yaw angle [rad]"
    yaw::MyFloat = 0
    "generic variable 01"
    var_01::MyFloat = 0
    "generic variable 02"
    var_02::MyFloat = 0
    "generic variable 03"
    var_03::MyFloat = 0
    "generic variable 04"
    var_04::MyFloat = 0
    "generic variable 05"
    var_05::MyFloat = 0
    "generic variable 06"
    var_06::MyFloat = 0
    "generic variable 07"
    var_07::MyFloat = 0
    "generic variable 08"
    var_08::MyFloat = 0
    "generic variable 09"
    var_09::MyFloat = 0
    "generic variable 10"
    var_10::MyFloat = 0
    "generic variable 11"
    var_11::MyFloat = 0
    "generic variable 12"
    var_12::MyFloat = 0
    "generic variable 13"
    var_13::MyFloat = 0
    "generic variable 14"
    var_14::MyFloat = 0
    "generic variable 15"
    var_15::MyFloat = 0
    "generic variable 16"
    var_16::MyFloat = 0
end
